export const PROJECTS_DATA = [
    {
        title: 'The Daily Muck',
        link: 'https://dailymuck.com/',
        description: `For this project, I was responsible for the complete frontend and backend development, following a pre-designed layout in Figma. The website was built using WordPress and is dedicated to a news agency with a strong focus on political content.`,
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Figma'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: 'Bureau TwentyTwo',
        link: 'https://b22.io/',
        description: `This project was executed as a redesign of the website for the Bureau Twentytwo agency. I handled all aspects of the project, including frontend, backend, responsiveness, SEO, and robots.txt.`,
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP', 'SEO'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: 'Plant By Number',
        link: 'https://pbndesign.com/',
        description: `On this project, I implemented the complete frontend based on the design created in Figma. I also worked on the responsiveness and made some minor changes to the backend.`,
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: '3ap',
        link: 'https://3ap.ch/',
        description: `The website was developed based on the client's design, where I handled the entire site, including the frontend, animations, responsiveness, and backend. It was implemented in two languages, English and German.`,
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: 'Lucha T8',
        link: 'https://luchat8.com/',
        description: `On this project, I worked on the complete frontend according to the design created in Figma, focusing on the site's responsiveness and adding multiple languages.`,
        technologies: ['HTML', 'CSS', 'JavaScript'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: 'Executive Assistants',
        link: 'https://www.execassistance.com/',
        description: `On this project, I was responsible for the entire frontend, implementing all visual elements and interactive animations. I also ensured that the site was fully responsive, providing users with an optimal experience across various devices.`,
        technologies: ['HTML', 'CSS', 'JavaScript'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
    {
        title: 'Seawall Point',
        link: 'https://seawall-point.com/',
        description: `In this project, I was in charge of the complete frontend, where I developed all visual components and interactive animations. Additionally, I focused on optimizing the site’s responsiveness to ensure users had an excellent experience across various devices.`,
        technologies: ['HTML', 'CSS', 'JavaScript'],
        notes: 'This project was designed and developed within the B22 agency.',
    },
];
